CREATE DATABASE BanNoiThat
GO
USE BanNoiThat
GO

CREATE TABLE Account
(
AccountID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
TaiKhoan VARCHAR(100) NOT NULL,
MatKhau VARCHAR(30) NOT NULL,
Phone INT NOT NULL,
Email VARCHAR(24) NOT NULL,
FullName NVARCHAR(100) NOT NULL,
CreateDate DATE NOT NULL
)
GO

CREATE TABLE DanhMucSP
(
MaDM INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
TenDM NVARCHAR(200) NOT NULL,
AnhDM NVARCHAR(MAX),
MoTaDM NVARCHAR(500),
TrangThai BIT
)
GO

CREATE TABLE SanPham
(
MaSP INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
MaDM INT,
TenSP NVARCHAR(200) NOT NULL,
AnhSP NVARCHAR(MAX) NOT NULL,
VideoSP NVARCHAR(MAX),
GiaSP INT NOT NULL,
TrangThai BIT NOT NULL,
BestSeller BIT NOT NULL,
CreateDate DATE NOT NULL,
NgaySua DATE NOT NULL,
LinkDownGame Nvarchar(Max),
MotaSP NVARCHAR(MAX) NOT NULL

FOREIGN KEY (MaDM) REFERENCES DanhMucSP(MaDM)
)
GO

CREATE TABLE KhachHang
(
MaKH INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
TenKH NVARCHAR(200) NOT NULL,
Diachi NVARCHAR(500) NOT NULL,
Ngaysinh DATE NOT NULL,
Phone INT NOT NULL,
Email NVARCHAR(200) NOT NULL,
CreateDate DATE NOT NULL
)
GO

CREATE TABLE DonHang
(
MaDH INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
MaKH INT NOT NULL,
NgayTao DATE NOT NULL,
TrangThaiHuyDon BIT NOT NULL,
ThanhToan BIT NOT NULL,
NgayThanhToan DATE NOT NULL,
Note NVARCHAR(MAX)

FOREIGN KEY (MaKH) REFERENCES dbo.KhachHang(MaKH)
)
GO

CREATE TABLE ChiTietDonHang
(
MaCTDH INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
MaDH INT NOT NULL,
MaSP INT NOT NULL,
TongTien INT NOT NULL,
Ngaygiao INT NOT NULL

FOREIGN KEY (MaDH) REFERENCES dbo.DonHang(MaDH),
FOREIGN KEY (MaSP) REFERENCES dbo.SanPham(MaSP)
)
GO

SET IDENTITY_INSERT [dbo].[DanhMucSP] ON 

INSERT [dbo].[DanhMucSP] ([MaDM], [TenDM], [AnhDM], [MoTaDM], [TrangThai]) VALUES (1, N'Bàn Nội Thất', NULL, N'Các loại bàn nội thất', 1)
INSERT [dbo].[DanhMucSP] ([MaDM], [TenDM], [AnhDM], [MoTaDM], [TrangThai]) VALUES (2, N'Ghế Nội Thất', NULL, N'Các loại ghế nội thất', 1)
INSERT [dbo].[DanhMucSP] ([MaDM], [TenDM], [AnhDM], [MoTaDM], [TrangThai]) VALUES (3, N'Bóng Đèn', NULL, N'Các bóng đèn nội thất', 1)
SET IDENTITY_INSERT [dbo].[DanhMucSP] OFF
GO
